CREATE TYPE requirement_status AS ENUM ('DRAFT','READY','ARCHIVED');
CREATE TYPE run_status AS ENUM ('PENDING','RUNNING','BLOCKED','COMPLETED','FAILED');
CREATE TYPE stage_outcome AS ENUM ('PENDING','LEASED','SUCCEEDED','FAILED','EXPIRED');

CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), name varchar(120) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), project_id uuid NOT NULL REFERENCES projects(id), statement text NOT NULL CHECK(length(statement) BETWEEN 10 AND 10000), status requirement_status NOT NULL DEFAULT 'READY', idempotency_key varchar(200) NOT NULL, request_digest char(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(project_id,idempotency_key));
CREATE TABLE acceptance_criteria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), requirement_id uuid NOT NULL REFERENCES requirements(id), ordinal int NOT NULL CHECK(ordinal>0), description text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(requirement_id,ordinal));
CREATE TABLE runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), requirement_id uuid NOT NULL REFERENCES requirements(id), status run_status NOT NULL DEFAULT 'PENDING', current_stage varchar(40) NOT NULL DEFAULT 'RECEIVED', version bigint NOT NULL DEFAULT 0, idempotency_key varchar(200) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(requirement_id,idempotency_key));
CREATE TABLE stage_executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), run_id uuid NOT NULL REFERENCES runs(id), stage varchar(40) NOT NULL, attempt int NOT NULL CHECK(attempt>0), outcome stage_outcome NOT NULL DEFAULT 'PENDING', worker_id varchar(120), lease_token uuid, lease_expires_at timestamptz, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(run_id,stage,attempt));
CREATE UNIQUE INDEX one_active_stage_attempt ON stage_executions(run_id,stage) WHERE outcome IN ('PENDING','LEASED','SUCCEEDED');
CREATE TABLE agent_assignments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), run_id uuid NOT NULL REFERENCES runs(id), role varchar(80) NOT NULL, execution_identity varchar(160) NOT NULL, capability_scope jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE findings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), run_id uuid NOT NULL REFERENCES runs(id), supersedes_id uuid REFERENCES findings(id), severity varchar(20) NOT NULL, description text NOT NULL, disposition varchar(40) NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE gate_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), run_id uuid NOT NULL REFERENCES runs(id), gate varchar(80) NOT NULL, attempt int NOT NULL, result varchar(20) NOT NULL, evidence_record_id uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(run_id,gate,attempt));
CREATE TABLE evidence_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), run_id uuid NOT NULL REFERENCES runs(id), requirement_id uuid NOT NULL REFERENCES requirements(id), evidence_type varchar(80) NOT NULL, digest varchar(71) NOT NULL CHECK(digest ~ '^sha256:[0-9a-f]{64}$'), source_commit varchar(64), artifact_digest varchar(255), payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE gate_results ADD CONSTRAINT gate_evidence_fk FOREIGN KEY(evidence_record_id) REFERENCES evidence_records(id);
CREATE TABLE audit_events (sequence bigserial PRIMARY KEY, id uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), aggregate_type varchar(40) NOT NULL, aggregate_id uuid NOT NULL, event_type varchar(100) NOT NULL, actor varchar(160) NOT NULL, payload jsonb NOT NULL DEFAULT '{}', occurred_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_aggregate_history ON audit_events(aggregate_type,aggregate_id,sequence);
CREATE TABLE outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_version int NOT NULL DEFAULT 1 CHECK(schema_version=1), aggregate_type varchar(40) NOT NULL, aggregate_id uuid NOT NULL, event_type varchar(100) NOT NULL, payload jsonb NOT NULL, attempts int NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(), claimed_by varchar(120), claim_expires_at timestamptz, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_available ON outbox_events(available_at,created_at) WHERE published_at IS NULL;

CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit_events is append-only'; END $$;
CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();
