import { createHash, sign, verify, type KeyObject } from "node:crypto";
import { z } from "zod";
import { canonicalJson } from "../../../packages/evidence/src/index";

const digest = z.string().regex(/^sha256:[a-f0-9]{64}$/);
export const workerStages = ["DEVELOPER", "CRITIC", "SECURITY", "QA"] as const;
export const jobManifestSchema = z.object({ schemaVersion: z.literal("worker-job.v1"), jobId: z.string().uuid(), runId: z.string().uuid(), executionId: z.string().uuid(), stage: z.enum(workerStages), repository: z.object({ slug: z.string().regex(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/), ref: z.string().min(1).max(200) }).strict(), issuedAt: z.string().datetime(), expiresAt: z.string().datetime(), inputs: z.array(z.object({ name: z.string().min(1).max(100), digest }).strict()).max(100), policyDigest: digest, allowedCommands: z.array(z.array(z.string().min(1).max(500)).min(1).max(30)).max(30), requiredChecks: z.array(z.string().min(1).max(100)).max(30), networkAllowlist: z.array(z.string().url()).max(10), writablePaths: z.array(z.string().regex(/^\/workspace\/(?:output|repository)(?:\/[A-Za-z0-9_.-]+)*$/).refine((path) => !path.split("/").some((part) => part === "." || part === ".."), "Path traversal is forbidden")).max(10) }).strict();
export type JobManifest = z.infer<typeof jobManifestSchema>;
export type SignedJobManifest = { manifest: JobManifest; signature: string; keyId: string };
export function signManifest(manifest: JobManifest, privateKey: KeyObject, keyId: string): SignedJobManifest { jobManifestSchema.parse(manifest); return { manifest, keyId, signature: sign(null, Buffer.from(canonicalJson(manifest)), privateKey).toString("base64") }; }
export function verifyManifest(envelope: SignedJobManifest, publicKey: KeyObject, now = new Date(), expectedPolicyDigest?: string): JobManifest { const manifest = jobManifestSchema.parse(envelope.manifest); if (!verify(null, Buffer.from(canonicalJson(manifest)), publicKey, Buffer.from(envelope.signature, "base64"))) throw new Error("Invalid job manifest signature"); if (Date.parse(manifest.expiresAt) <= now.getTime()) throw new Error("Job manifest expired"); if (Date.parse(manifest.issuedAt) > now.getTime() + 60_000) throw new Error("Job manifest issued in future"); if (expectedPolicyDigest && manifest.policyDigest !== expectedPolicyDigest) throw new Error("Worker policy mismatch"); return manifest; }
export function contentDigest(content: Uint8Array | string): `sha256:${string}` { return `sha256:${createHash("sha256").update(content).digest("hex")}`; }
export function assertSeparateExecutions(jobs: readonly JobManifest[]) { const byStage = new Set(jobs.map((job) => job.stage)); const executions = new Set(jobs.map((job) => job.executionId)); if (byStage.size !== 4 || executions.size !== jobs.length) throw new Error("Developer, Critic, Security and QA require separate executions"); }
