import assert from "node:assert/strict";
import { readFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { canTransition, projectCreateSchema, requirementCreateSchema } from "../../packages/contracts/src/index";
import { evidenceDigest } from "../../packages/evidence/src/index";
import type { Queryable, Transactional } from "../../packages/database/src/client";
import { ControlPlaneError, ControlPlaneStore } from "../../services/orchestrator/src/store";
import { resumeIncompleteRuns } from "../../services/orchestrator/src/tick";

const up=await readFile(new URL("../../infra/postgres/migrations/0001_m1_control_plane.up.sql",import.meta.url),"utf8");
const down=await readFile(new URL("../../infra/postgres/migrations/0001_m1_control_plane.down.sql",import.meta.url),"utf8");
function adapter(db:PGlite):Transactional{return {query:async(text,values)=>db.query(text,values as never[]) as never,transaction:work=>db.transaction(async tx=>work(tx as unknown as Queryable))};}
async function fixture(){const db=new PGlite();await db.exec(up);const store=new ControlPlaneStore(adapter(db));const project=await store.createProject("M1 laboratory");const requirement=await store.createRequirement(project.id,{statement:"Persist this requirement through all process restarts.",acceptanceCriteria:["Run state remains durable"]},"requirement-key-0001");const run=await store.startRun(requirement.id,"run-key-0001");return {db,store,project,requirement,run};}

test("versioned contracts reject unknown and malformed values",()=>{assert.equal(projectCreateSchema.safeParse({name:"x",authority:true}).success,false);assert.equal(requirementCreateSchema.safeParse({statement:"short",acceptanceCriteria:[]}).success,false);assert.equal(canTransition("RECEIVED","SPECIFIED"),true);assert.equal(canTransition("RECEIVED","DESIGNED"),false);assert.match(evidenceDigest({b:2,a:1}),/^sha256:[a-f0-9]{64}$/);});

test("migration applies and rolls back",async()=>{const db=new PGlite();await db.exec(up);assert.equal((await db.query("SELECT count(*)::int count FROM projects")).rows[0].count,0);await db.exec(down);await assert.rejects(()=>db.query("SELECT * FROM projects"));await db.close();});

test("idempotent requirement and run creation survive repository restart",async()=>{const {db,store,project,requirement,run}=await fixture();const duplicate=await store.createRequirement(project.id,{statement:"Persist this requirement through all process restarts.",acceptanceCriteria:["Run state remains durable"]},"requirement-key-0001");assert.equal(duplicate.id,requirement.id);const restarted=new ControlPlaneStore(adapter(db));const duplicateRun=await restarted.startRun(requirement.id,"run-key-0001");assert.equal(duplicateRun.id,run.id);assert.equal((await db.query("SELECT count(*)::int count FROM requirements")).rows[0].count,1);await db.close();});

test("concurrent leasing has one winner and expired lease is reclaimed with audit",async()=>{const {db,store,run}=await fixture();const settled=await Promise.allSettled([store.lease(run.id,"worker-a",30),store.lease(run.id,"worker-b",30)]);assert.equal(settled.filter(x=>x.status==="fulfilled").length,1);const first=settled.find(x=>x.status==="fulfilled") as PromiseFulfilledResult<{id:string}>;await db.query("UPDATE stage_executions SET lease_expires_at=now()-interval '1 second' WHERE id=$1",[first.value.id]);const reclaimed=await store.lease(run.id,"worker-c",30) as {attempt:number};assert.equal(reclaimed.attempt,2);const history=await db.query<{event_type:string}>("SELECT event_type FROM audit_events WHERE aggregate_id=$1",[run.id]);assert.ok(history.rows.some(e=>e.event_type==="STAGE_LEASE_EXPIRED"));await db.close();});

test("duplicate completion cannot advance twice and rejection is audited",async()=>{const {db,store,run}=await fixture();const lease=await store.lease(run.id,"worker-a",30) as {id:string;lease_token:string};const input={workerId:"worker-a",leaseToken:lease.lease_token,outcome:"SUCCEEDED" as const};const result=await store.complete(run.id,lease.id,input);assert.equal(result?.currentStage,"SPECIFIED");await assert.rejects(()=>store.complete(run.id,lease.id,input),(error:ControlPlaneError)=>error.code==="INVALID_LEASE");assert.equal((await db.query("SELECT count(*)::int count FROM runs WHERE id=$1 AND current_stage='SPECIFIED' AND version=1",[run.id])).rows[0].count,1);assert.equal((await db.query("SELECT count(*)::int count FROM audit_events WHERE aggregate_id=$1 AND event_type='STAGE_COMPLETION_REJECTED'",[run.id])).rows[0].count,1);await db.close();});

test("invalid transition fails closed and remains in append-only audit",async()=>{const {db,store,run}=await fixture();const lease=await store.lease(run.id,"worker-a",30) as {id:string;lease_token:string};await db.query("UPDATE runs SET current_stage='DESIGNED' WHERE id=$1",[run.id]);await assert.rejects(()=>store.complete(run.id,lease.id,{workerId:"worker-a",leaseToken:lease.lease_token,outcome:"SUCCEEDED"}),(error:ControlPlaneError)=>error.code==="INVALID_TRANSITION");assert.equal((await db.query("SELECT count(*)::int count FROM audit_events WHERE aggregate_id=$1 AND event_type='INVALID_TRANSITION_REJECTED'",[run.id])).rows[0].count,1);await assert.rejects(()=>db.query("DELETE FROM audit_events WHERE aggregate_id=$1",[run.id]));await db.close();});

test("orchestrator restart repairs missing pending execution without duplicate side effects",async()=>{const directory=await mkdtemp(join(tmpdir(),"dx-m1-"));let db=new PGlite(`file://${directory}`);await db.exec(up);const store=new ControlPlaneStore(adapter(db));const project=await store.createProject("Restart");const req=await store.createRequirement(project.id,{statement:"Resume this workflow after orchestrator restart.",acceptanceCriteria:["Exactly one stage is pending"]},"restart-req-key");const run=await store.startRun(req.id,"restart-run-key");await db.query("DELETE FROM stage_executions WHERE run_id=$1",[run.id]);await db.close();db=new PGlite(`file://${directory}`);assert.equal(await resumeIncompleteRuns(adapter(db)),1);assert.equal(await resumeIncompleteRuns(adapter(db)),0);assert.equal((await db.query("SELECT count(*)::int count FROM stage_executions WHERE run_id=$1",[run.id])).rows[0].count,1);await db.close();await rm(directory,{recursive:true,force:true});});
