import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { PostgresTelemetrySink } from "../../services/omniroute/src/postgres-telemetry";
const m1=await readFile(new URL("../../infra/postgres/migrations/0001_m1_control_plane.up.sql",import.meta.url),"utf8");
const up=await readFile(new URL("../../infra/postgres/migrations/0002_m2_omniroute.up.sql",import.meta.url),"utf8");
const down=await readFile(new URL("../../infra/postgres/migrations/0002_m2_omniroute.down.sql",import.meta.url),"utf8");
test("M2 migration stores replay-safe digest-only telemetry and rolls back",async()=>{const db=new PGlite();await db.exec(m1);await db.exec(up);const project=(await db.query<{id:string}>("INSERT INTO projects(name) VALUES('test') RETURNING id")).rows[0];const requirement=(await db.query<{id:string}>("INSERT INTO requirements(project_id,statement,idempotency_key,request_digest) VALUES($1,'A sufficiently long test requirement','req-key-1',$2) RETURNING id",[project.id,"a".repeat(64)])).rows[0];const run=(await db.query<{id:string}>("INSERT INTO runs(requirement_id,idempotency_key) VALUES($1,'run-key-1') RETURNING id",[requirement.id])).rows[0];const sink=new PostgresTelemetrySink(db as never,run.id);const event={idempotencyKey:"same-key",requestedRoute:"requirements" as const,effectiveModel:"mock",latencyMs:2,fallback:false,promptVersion:"po.v1",inputDigest:`sha256:${"b".repeat(64)}`,outputDigest:`sha256:${"c".repeat(64)}`,result:"SUCCEEDED" as const};await sink.record(event);await sink.record(event);assert.equal((await db.query<{count:number}>("SELECT count(*)::int count FROM model_invocations")).rows[0].count,1);await db.exec(down);await assert.rejects(()=>db.query("SELECT * FROM model_invocations"));await db.close();});

import { OmniRouteAdapter } from "../../services/omniroute/src/adapter";
import type { ModelProvider } from "../../services/omniroute/src/types";
import { SpecificationWorkflow } from "../../services/agents/src/specification-workflow";
import { runPersistedRequirement } from "../../services/agents/src/persisted-runner";
test("a persisted requirement becomes replay-safe reviewed artifacts",async()=>{const db=new PGlite();await db.exec(m1);await db.exec(up);const project=(await db.query<{id:string}>("INSERT INTO projects(name) VALUES('test') RETURNING id")).rows[0];const requirement=(await db.query<{id:string}>("INSERT INTO requirements(project_id,statement,idempotency_key,request_digest) VALUES($1,'Persist a reviewed specification and plan','req-key-2',$2) RETURNING id",[project.id,"d".repeat(64)])).rows[0];await db.query("INSERT INTO acceptance_criteria(requirement_id,ordinal,description) VALUES($1,1,'Artifacts are durable')",[requirement.id]);const run=(await db.query<{id:string}>("INSERT INTO runs(requirement_id,idempotency_key) VALUES($1,'run-key-2') RETURNING id",[requirement.id])).rows[0];const spec={schemaVersion:"specification.v1",title:"Durable artifacts",summary:"Persist reviewed specification artifacts safely.",assumptions:[],acceptanceCriteria:[{id:"AC-01",statement:"Artifacts are durable",verification:"Read stored rows"}],outOfScope:[]};const plan={schemaVersion:"implementation-plan.v1",architecture:"Use the additive generated artifacts table.",decisions:[{id:"DEC-01",decision:"Use PostgreSQL",rationale:"It supplies durable state"}],tasks:[{id:"TASK-01",description:"Persist each artifact",acceptanceCriteria:["AC-01"],dependsOn:[]}],risks:[],rollback:"Drop additive records after export"};const provider:ModelProvider={async complete(request){const envelope=JSON.parse(request.messages[1].content);const content=request.route==="requirements"?spec:request.route==="architecture"?plan:request.route==="critic"?{schemaVersion:"critic-review.v1",verdict:"ACCEPT",findings:[]}:{schemaVersion:"judge-decision.v1",verdict:"PASS",evaluatedDigests:envelope.content.digests,reasons:["Evidence matches"]};return {content:JSON.stringify(content),model:request.route,modelFamily:["critic","judge"].includes(request.route)?`verify-${request.route}`:"author",usage:{inputTokens:1,outputTokens:1}};}};const adapter=new OmniRouteAdapter(provider,{async record(){}});const outcome=await runPersistedRequirement(db as never,new SpecificationWorkflow(adapter),run.id,{maxCalls:8,maxTokens:100,deadline:new Date(Date.now()+5000)});assert.equal(outcome.state,"REVIEWED");assert.equal((await db.query<{count:number}>("SELECT count(*)::int count FROM generated_artifacts WHERE run_id=$1",[run.id])).rows[0].count,5);await runPersistedRequirement(db as never,new SpecificationWorkflow(adapter),run.id,{maxCalls:8,maxTokens:100,deadline:new Date(Date.now()+5000)});assert.equal((await db.query<{count:number}>("SELECT count(*)::int count FROM generated_artifacts WHERE run_id=$1",[run.id])).rows[0].count,5);await db.close();});
