import { createHash, randomUUID } from "node:crypto";
import { canTransition, stageNames, type StageName } from "../../../packages/contracts/src/index";
import type { Queryable, Transactional } from "../../../packages/database/src/client";

export class ControlPlaneError extends Error { constructor(public code: string, message: string, public status = 409) { super(message); } }
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
const nextStage = (stage: StageName): StageName | undefined => stageNames[stageNames.indexOf(stage) + 1];
async function audit(tx: Queryable, aggregateType: string, aggregateId: string, eventType: string, actor: string, payload: unknown = {}) {
  await tx.query("INSERT INTO audit_events(aggregate_type,aggregate_id,event_type,actor,payload) VALUES($1,$2,$3,$4,$5::jsonb)", [aggregateType, aggregateId, eventType, actor, JSON.stringify(payload)]);
}
async function outbox(tx: Queryable, aggregateType: string, aggregateId: string, eventType: string, payload: unknown) {
  await tx.query("INSERT INTO outbox_events(aggregate_type,aggregate_id,event_type,payload) VALUES($1,$2,$3,$4::jsonb)", [aggregateType, aggregateId, eventType, JSON.stringify(payload)]);
}

export class ControlPlaneStore {
  constructor(private db: Transactional) {}
  async createProject(name: string) {
    return this.db.transaction(async tx => { const result = await tx.query<{id:string;name:string;created_at:string}>("INSERT INTO projects(name) VALUES($1) RETURNING id,name,created_at", [name]); const project=result.rows[0]; await audit(tx,"PROJECT",project.id,"PROJECT_CREATED","api",{name}); await outbox(tx,"PROJECT",project.id,"PROJECT_CREATED",project); return project; });
  }
  async createRequirement(projectId: string, input: {statement:string;acceptanceCriteria:string[]}, key: string) {
    return this.db.transaction(async tx => {
      const requestDigest=digest(input); const existing=await tx.query<{id:string;request_digest:string}>("SELECT id,request_digest FROM requirements WHERE project_id=$1 AND idempotency_key=$2 FOR UPDATE",[projectId,key]);
      if(existing.rows[0]) { if(existing.rows[0].request_digest!==requestDigest) throw new ControlPlaneError("IDEMPOTENCY_CONFLICT","Idempotency key was already used with a different request"); return this.getRequirement(existing.rows[0].id,tx); }
      const inserted=await tx.query<{id:string;project_id:string;statement:string;status:string;created_at:string}>("INSERT INTO requirements(project_id,statement,idempotency_key,request_digest) VALUES($1,$2,$3,$4) ON CONFLICT(project_id,idempotency_key) DO NOTHING RETURNING id,project_id,statement,status,created_at",[projectId,input.statement,key,requestDigest]); const requirement=inserted.rows[0]; if(!requirement) { const raced=await tx.query<{id:string;request_digest:string}>("SELECT id,request_digest FROM requirements WHERE project_id=$1 AND idempotency_key=$2",[projectId,key]); if(raced.rows[0]?.request_digest!==requestDigest) throw new ControlPlaneError("IDEMPOTENCY_CONFLICT","Idempotency key was already used with a different request"); return this.getRequirement(raced.rows[0].id,tx); }
      for(const [index,description] of input.acceptanceCriteria.entries()) await tx.query("INSERT INTO acceptance_criteria(requirement_id,ordinal,description) VALUES($1,$2,$3)",[requirement.id,index+1,description]);
      await audit(tx,"REQUIREMENT",requirement.id,"REQUIREMENT_CREATED","api",{projectId}); await outbox(tx,"REQUIREMENT",requirement.id,"REQUIREMENT_CREATED",{requirementId:requirement.id}); return this.getRequirement(requirement.id,tx);
    });
  }
  private async getRequirement(id:string,tx:Queryable=this.db): Promise<{id:string;project_id:string;statement:string;status:string;created_at:string;acceptanceCriteria:Record<string,unknown>[]}> { const req=await tx.query<{id:string;project_id:string;statement:string;status:string;created_at:string}>("SELECT id,project_id,statement,status,created_at FROM requirements WHERE id=$1",[id]); const criteria=await tx.query("SELECT id,ordinal,description FROM acceptance_criteria WHERE requirement_id=$1 ORDER BY ordinal",[id]); return {...req.rows[0],acceptanceCriteria:criteria.rows}; }
  async startRun(requirementId:string,key:string) {
    return this.db.transaction(async tx=>{ const prior=await tx.query("SELECT * FROM runs WHERE requirement_id=$1 AND idempotency_key=$2 FOR UPDATE",[requirementId,key]); if(prior.rows[0]) return prior.rows[0]; const result=await tx.query<{id:string;requirement_id:string;status:string;current_stage:StageName;version:number;idempotency_key:string;created_at:string;updated_at:string}>("INSERT INTO runs(requirement_id,status,current_stage,idempotency_key) VALUES($1,'RUNNING','RECEIVED',$2) ON CONFLICT(requirement_id,idempotency_key) DO NOTHING RETURNING *",[requirementId,key]); const run=result.rows[0]; if(!run) return (await tx.query("SELECT * FROM runs WHERE requirement_id=$1 AND idempotency_key=$2",[requirementId,key])).rows[0]; await tx.query("INSERT INTO stage_executions(run_id,stage,attempt) VALUES($1,'RECEIVED',1)",[run.id]); await audit(tx,"RUN",run.id,"RUN_STARTED","api",{requirementId}); await outbox(tx,"RUN",run.id,"STAGE_READY",{stage:"RECEIVED"}); return run; });
  }
  async lease(runId:string,workerId:string,seconds:number) {
    return this.db.transaction(async tx=>{ const run=await tx.query<{current_stage:StageName}>("SELECT current_stage FROM runs WHERE id=$1 AND status='RUNNING' FOR UPDATE",[runId]); if(!run.rows[0]) throw new ControlPlaneError("RUN_NOT_AVAILABLE","Run is not available",404); const expired=await tx.query<{id:string;attempt:number}>("UPDATE stage_executions SET outcome='EXPIRED' WHERE run_id=$1 AND stage=$2 AND outcome='LEASED' AND lease_expires_at<=now() RETURNING id,attempt",[runId,run.rows[0].current_stage]); if(expired.rows[0]) { await audit(tx,"RUN",runId,"STAGE_LEASE_EXPIRED","orchestrator",expired.rows[0]); await tx.query("INSERT INTO stage_executions(run_id,stage,attempt) VALUES($1,$2,$3)",[runId,run.rows[0].current_stage,expired.rows[0].attempt+1]); }
      const token=randomUUID(); const leased=await tx.query("UPDATE stage_executions SET outcome='LEASED',worker_id=$3,lease_token=$4,lease_expires_at=now()+($5 * interval '1 second'),started_at=COALESCE(started_at,now()) WHERE run_id=$1 AND stage=$2 AND outcome='PENDING' RETURNING *",[runId,run.rows[0].current_stage,workerId,token,seconds]); if(!leased.rows[0]) throw new ControlPlaneError("LEASE_UNAVAILABLE","Stage is already leased"); await audit(tx,"RUN",runId,"STAGE_LEASED",workerId,{stage:run.rows[0].current_stage,attempt:(leased.rows[0] as {attempt:number}).attempt}); return leased.rows[0]; });
  }
  async complete(runId:string,stageId:string,input:{workerId:string;leaseToken:string;outcome:"SUCCEEDED"|"FAILED";evidenceDigest?:string}) {
    const result=await this.db.transaction(async tx=>{ const runResult=await tx.query<{id:string;current_stage:StageName;version:number}>("SELECT id,current_stage,version FROM runs WHERE id=$1 FOR UPDATE",[runId]); const run=runResult.rows[0]; if(!run) return {error:new ControlPlaneError("RUN_NOT_FOUND","Run not found",404)}; const stageResult=await tx.query<{id:string;stage:StageName;outcome:string;worker_id:string;lease_token:string;lease_expires_at:string}>("SELECT * FROM stage_executions WHERE id=$1 AND run_id=$2 FOR UPDATE",[stageId,runId]); const stage=stageResult.rows[0];
      if(!stage || stage.outcome!=="LEASED" || stage.worker_id!==input.workerId || stage.lease_token!==input.leaseToken || new Date(stage.lease_expires_at)<=new Date()) { await audit(tx,"RUN",runId,"STAGE_COMPLETION_REJECTED",input.workerId,{stageId,reason:"invalid_or_expired_lease"}); return {error:new ControlPlaneError("INVALID_LEASE","Lease is invalid, expired, or already completed")}; }
      if(stage.stage!==run.current_stage) { await audit(tx,"RUN",runId,"INVALID_TRANSITION_REJECTED",input.workerId,{from:run.current_stage,submitted:stage.stage}); return {error:new ControlPlaneError("INVALID_TRANSITION","Stage does not match current run state")}; }
      await tx.query("UPDATE stage_executions SET outcome=$2,completed_at=now() WHERE id=$1",[stageId,input.outcome]); await audit(tx,"RUN",runId,"STAGE_COMPLETED",input.workerId,{stage:stage.stage,outcome:input.outcome,evidenceDigest:input.evidenceDigest});
      if(input.outcome==="FAILED") { await tx.query("UPDATE runs SET status='BLOCKED',version=version+1,updated_at=now() WHERE id=$1",[runId]); await outbox(tx,"RUN",runId,"RUN_BLOCKED",{stage:stage.stage}); return {data:{status:"BLOCKED",currentStage:stage.stage}}; }
      const next=nextStage(stage.stage); if(!next) { await tx.query("UPDATE runs SET status='COMPLETED',version=version+1,updated_at=now() WHERE id=$1",[runId]); await outbox(tx,"RUN",runId,"RUN_COMPLETED",{}); return {data:{status:"COMPLETED",currentStage:stage.stage}}; }
      if(!canTransition(stage.stage,next)) { await audit(tx,"RUN",runId,"INVALID_TRANSITION_REJECTED","orchestrator",{from:stage.stage,to:next}); return {error:new ControlPlaneError("INVALID_TRANSITION","Transition is not allowed")}; }
      await tx.query("UPDATE runs SET current_stage=$2,version=version+1,updated_at=now() WHERE id=$1 AND version=$3",[runId,next,run.version]); await tx.query("INSERT INTO stage_executions(run_id,stage,attempt) VALUES($1,$2,1)",[runId,next]); await audit(tx,"RUN",runId,"RUN_TRANSITIONED","orchestrator",{from:stage.stage,to:next}); await outbox(tx,"RUN",runId,"STAGE_READY",{stage:next}); return {data:{status:"RUNNING",currentStage:next}};
    }); if(result.error) throw result.error; return result.data;
  }
  async snapshot() { const projects=await this.db.query("SELECT * FROM projects ORDER BY created_at DESC"); const runs=await this.db.query("SELECT r.*,q.statement,p.name project_name FROM runs r JOIN requirements q ON q.id=r.requirement_id JOIN projects p ON p.id=q.project_id ORDER BY r.created_at DESC"); const stages=await this.db.query("SELECT * FROM stage_executions ORDER BY created_at,attempt"); const auditEvents=await this.db.query("SELECT * FROM audit_events ORDER BY sequence DESC LIMIT 100"); return {projects:projects.rows,runs:runs.rows,stages:stages.rows,auditEvents:auditEvents.rows}; }
}
